videostore/accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns


from rest_framework_jwt.views import refresh_jwt_token, obtain_jwt_token # accounts app

from .views import AuthAPIView, RegisterAPIView, logout_view
urlpatterns = [
    url(r'^login/$', AuthAPIView.as_view(), name='login'),
    url(r'^register/$', RegisterAPIView.as_view(), name='register'),
    url(r'^jwt/$', obtain_jwt_token),
    url(r'^jwt/refresh/$', refresh_jwt_token),
    url(r'^logout/$', logout_view, name='logout'),
]

app_name = 'accounts'

urlpatterns = format_suffix_patterns(urlpatterns)

videostore/rentaldvd/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^api/$', views.RentalRestAPIView.as_view(), name='dvd_api'),
    url(r'^api/(?P<id>\d+)/$', views.RentalAPIDetailView.as_view()),
    url(r'^dvd/(?P<id>[0-9]+)/$', views.DvdDetailView.as_view(), name='detail'),

    url(r'^$', views.DvdListView.as_view(), name='home'),

]

app_name = 'rentaldvd'

urlpatterns = format_suffix_patterns(urlpatterns)

videostore/videostore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'videostore.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rentaldvd.urls', namespace='api-polls', app_name='rentaldvd')),
    url(r'^api/auth/', include('accounts.urls', namespace='api-auth')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videostore/accounts/models.py
from django.db import models

# Create your models here.

videostore/rentaldvd/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save, post_save
from django.utils import timezone
from django.db.models import Q

from django.conf import settings
AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class DvdQuerySet(models.QuerySet):
    pass


class DvdManager(models.Manager):
    def get_queryset(self):
        return DvdQuerySet(self.model, using=self._db)

    def search(self, query):
        lookups = Q(title__icontains=query)
        return self.filter(lookups).distinct()


class Dvd(models.Model):
    STATUS_CHOICES = (
        ('took', 'Took the disk'),
        ('returned', 'Returned disk'),
    )

    user            = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None, blank=True)
    title           = models.CharField(max_length=120)
    content         = models.TextField()
    status          = models.CharField(max_length=10, choices=STATUS_CHOICES, default='returned')
    date_took       = models.DateTimeField(auto_now_add=False, editable=True, default=timezone.now, blank=False)
    date_returned   = models.DateTimeField(auto_now_add=False, editable=True, default=timezone.now, blank=False)
    updated         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    objects = DvdManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("rentaldvd:detail", kwargs={"id": self.id})

videostore/rentaldvd/forms.py
from .models import Dvd
from django.forms import ModelForm
from django import forms
import django_filters


class DvdApiFilter(django_filters.FilterSet):
    title = django_filters.CharFilter(name='title')

    class Meta:
        model = Dvd
        fields = ('title',)

videostore/accounts/views.py
from django.shortcuts import redirect, render
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.db.models import Q
from rest_framework import generics, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework_jwt.settings import api_settings

from .serializers import UserRegisterSerializer

jwt_payload_handler             = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler              = api_settings.JWT_ENCODE_HANDLER
jwt_response_payload_handler    = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER

User = get_user_model()

class AuthAPIView(APIView):
    # permission_classes      = [AnonPermissionOnly]
    def post(self, request, *args, **kwargs):
        print(request.user.is_authenticated)
        if request.user.is_authenticated():
            return Response({'detail': 'You are already authenticated'}, status=400)

        data = request.data
        username = data.get('username') # username or email address
        password = data.get('password')
        qs = User.objects.filter(
                Q(username__iexact=username)|
                Q(email__iexact=username)
            ).distinct()
        if qs.count() == 1:
            user_obj = qs.first()
            if user_obj.check_password(password):
                user = user_obj
                payload = jwt_payload_handler(user)
                token = jwt_encode_handler(payload)
                response = jwt_response_payload_handler(token, user, request=request)
                user = authenticate(username=username, password=password)
                print(user)
                login(request, user)
                return Response(response)
        return Response({"detail": "Invalid credentials"}, status=401)


class RegisterAPIView(generics.CreateAPIView):
    queryset                = User.objects.all()
    serializer_class        = UserRegisterSerializer
    # permission_classes      = [AnonPermissionOnly]

    def get_serializer_context(self, *args, **kwargs):
        return {"request": self.request}


def logout_view(request):
    logout(request)
    return redirect(reverse('rentaldvd:home'))
    # Redirect to a success page.

videostore/rentaldvd/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View

import django_filters
from rest_framework import routers, serializers, viewsets, filters
from rest_framework import generics, mixins



from .serializers import DvdApiSerializer
from .forms import DvdApiFilter
from .models import Dvd



class RentalAPIDetailView(
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    generics.RetrieveAPIView):
    serializer_class            = DvdApiSerializer
    queryset                    = Dvd.objects.all()
    lookup_field                = 'id'

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class RentalRestAPIView(generics.ListAPIView, mixins.CreateModelMixin):
    # permission_classes = (IsAuthenticated,)
    queryset = Dvd.objects.order_by('updated')
    serializer_class = DvdApiSerializer
    filter_class = DvdApiFilter
    search_fields = ('title',)
    ordering_fields = ('title')
    filter_backends = (
        django_filters.rest_framework.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class DvdListView(ListView):
    template_name = 'home.html'
    queryset = Dvd.objects.all()


class DvdDetailView(DetailView):
    template_name = 'dvd_detail.html'

    def get_object(self):
        id_ = self.kwargs.get('id')

        return get_object_or_404(Dvd, id=id_)

videostore/rentaldvd/templates/dvd_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.content }}</p>
{% endblock %}

videostore/rentaldvd/templates/home.html
{% extends 'base.html' %}

{% block content %}






<div class="row mb-2">


    {% for instance in object_list %}



            <div class="col-md-6">
          <div class="card flex-md-row mb-4 shadow-sm h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">{{ instance.status }}</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{{ instance.get_absolute_url }}">{{ instance.title }}</a>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto">{{ instance.content }}</p>
              <a href="{{ instance.get_absolute_url }}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 200px; height: 250px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16687a07931%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16687a07931%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2255.609375%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
          </div>
        </div>
{% endfor %}

      </div>









    	<div class="row">
			<div class="col-md-6 col-md-offset-3">




			</div>
		</div>




{% endblock %}

videostore/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Coding for Entrepreneurs is doing Try Django</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/examples/blog/blog.css" >
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">

</head>
<body>
    <div class="container">
       {% include 'navbar.html' %}

       {% block content %}
        replace me
       {% endblock %}
    </div>
<footer class="blog-footer">
      <p>Blog template built for <a href="#">Bootstrap</a> by <a href="#">@</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-md-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-md-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="{% url 'api-auth:login' %}" method="post" role="form" style="display: block;">
									<div class="form-group">
										<input type="text" name="username" id="username1" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password1" tabindex="2" class="form-control" placeholder="Password">
									</div>

									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>

								</form>
								<form id="register-form" action="{% url 'api-auth:register' %}" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="password2" id="password2" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</body>

	<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="{% static 'custom.js' %}" ></script>
</html>

videostore/templates/navbar.html
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'rentaldvd:home' %}">Large</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="{% url 'rentaldvd:home' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>

              {% if request.user.is_authenticated %}
              <span>{{ request.user }} </span>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'api-auth:logout' %}">logout</a>
              {% else %}
                <a class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#exampleModal">Sign up</a>
              {% endif %}
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="#">World</a>
          <a class="p-2 text-muted" href="#">U.S.</a>
          <a class="p-2 text-muted" href="#">Technology</a>
          <a class="p-2 text-muted" href="#">Design</a>
          <a class="p-2 text-muted" href="#">Culture</a>
          <a class="p-2 text-muted" href="#">Business</a>
          <a class="p-2 text-muted" href="#">Politics</a>
          <a class="p-2 text-muted" href="#">Opinion</a>
          <a class="p-2 text-muted" href="#">Science</a>
          <a class="p-2 text-muted" href="#">Health</a>
          <a class="p-2 text-muted" href="#">Style</a>
          <a class="p-2 text-muted" href="#">Travel</a>
        </nav>
      </div>